sudo: required

services:
- docker

before_install:
- docker build -t vc-react/web:1.0 --build-arg CODECLIMATE_REPO_TOKEN=codeclimatetoken .
- docker run -d --name vc-react-container vc-react/web:1.0

script:
- docker ps -a